name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker build -t yii2-postman:latest -f ./tests/docker/Dockerfile ./tests/docker
      - name: Install composer packages
        run: docker run --rm --volume $PWD:/app yii2-postman:latest composer install
      - name: Run test suite
        run: docker run --rm --volume $PWD:/app yii2-postman:latest composer test
